Attribute VB_Name = "modConstants"
Option Explicit

Public Const SQLDMOScript_UseQuotedIdentifiers = -1
Public Const SQLDMOScript_None = 0
Public Const SQLDMOScript_Drops = 1
Public Const SQLDMOScript_ObjectPermissions = 2
Public Const SQLDMOScript_Default = 4
Public Const SQLDMOScript_PrimaryObject = 4
Public Const SQLDMOScript_ClusteredIndexes = 8
Public Const SQLDMOScript_Triggers = 16
Public Const SQLDMOScript_DatabasePermissions = 32
Public Const SQLDMOScript_Permissions = 34
Public Const SQLDMOScript_ToFileOnly = 64
Public Const SQLDMOScript_Bindings = 128
Public Const SQLDMOScript_AppendToFile = 256
Public Const SQLDMOScript_NoDRI = 512
Public Const SQLDMOScript_UDDTsToBaseType = 1024
Public Const SQLDMOScript_IncludeIfNotExists = 4096
Public Const SQLDMOScript_NonClusteredIndexes = 8192
Public Const SQLDMOScript_Aliases = 16384
Public Const SQLDMOScript_NoCommandTerm = 32768
Public Const SQLDMOScript_DRIIndexes = 65536
Public Const SQLDMOScript_Indexes = 73736
Public Const SQLDMOScript_IncludeHeaders = 131072
Public Const SQLDMOScript_OwnerQualify = 262144
Public Const SQLDMOScript_TransferDefault = 422143
Public Const SQLDMOScript_TimestampToBinary = 524288
Public Const SQLDMOScript_SortedData = 1048576
Public Const SQLDMOScript_SortedDataReorg = 2097152
Public Const SQLDMOScript_DRI_NonClustered = 4194304
Public Const SQLDMOScript_DRI_Clustered = 8388608
Public Const SQLDMOScript_DRI_Checks = 16777216
Public Const SQLDMOScript_DRI_Defaults = 33554432
Public Const SQLDMOScript_DRI_UniqueKeys = 67108864
Public Const SQLDMOScript_DRI_ForeignKeys = 134217728
Public Const SQLDMOScript_DRI_PrimaryKey = 268435456
Public Const SQLDMOScript_DRI_AllKeys = 469762048
Public Const SQLDMOScript_DRI_AllPublic_constraints = 520093696
Public Const SQLDMOScript_DRIWithNoCheck = 536870912
Public Const SQLDMOScript_DRI_All = 532676608
Public Const SQLDMOScript_NoIdentity = 1073741824

'enum SQLDMO.SQLDMO_SCRIPT2_TYPE
Public Const SQLDMOScript2_Default = 0
Public Const SQLDMOScript2_AnsiPadding = 1
Public Const SQLDMOScript2_AnsiFile = 2
Public Const SQLDMOScript2_UnicodeFile = 4
Public Const SQLDMOScript2_NonStop = 8
Public Const SQLDMOScript2_NoFG = 16
Public Const SQLDMOScript2_MarkTriggers = 32
Public Const SQLDMOScript2_OnlyUserTriggers = 64
Public Const SQLDMOScript2_EncryptPWD = 128
Public Const SQLDMOScript2_SeparateXPs = 256
Public Const SQLDMOScript2_NoWhatIfIndexes = 512
Public Const SQLDMOScript2_AgentNotify = 1024
Public Const SQLDMOScript2_AgentAlertJob = 2048
Public Const SQLDMOScript2_FullTextIndex = 524288
Public Const SQLDMOScript2_LoginSID = 1048576 'BOL is wrong, says 8192
Public Const SQLDMOScript2_FullTextCat = 2097152
Public Const SQLDMOScript2_ExtendedProperty = 4194304
Public Const SQLDMOScript2_NoCollation = 8388608
Public Const SQLDMOScript2_JobDisable = 33554432
Public Const SQLDMOScript2_ExtendedOnly = 67108864
Public Const SQLDMOScript2_70Only = 16777216
Public Const SQLDMOScript2_DontScriptJobServer = 134217728

'enum SQLDMO.SQLDMO_PRIVILEGE_TYPE
Public Const SQLDMOPriv_Unknown = 0
Public Const SQLDMOPriv_Select = 1
Public Const SQLDMOPriv_Insert = 2
Public Const SQLDMOPriv_Update = 4
Public Const SQLDMOPriv_Delete = 8
Public Const SQLDMOPriv_Execute = 16
Public Const SQLDMOPriv_References = 32
Public Const SQLDMOPriv_AllObjectPrivs = 63 'Default
Public Const SQLDMOPriv_CreateTable = 128
Public Const SQLDMOPriv_CreateDatabase = 256
Public Const SQLDMOPriv_CreateView = 512
Public Const SQLDMOPriv_CreateProcedure = 1024
Public Const SQLDMOPriv_DumpDatabase = 2048
Public Const SQLDMOPriv_CreateDefault = 4096
Public Const SQLDMOPriv_DumpTransaction = 8192
Public Const SQLDMOPriv_CreateRule = 16384
Public Const SQLDMOPriv_DumpTable = 32768
Public Const SQLDMOPriv_CreateFunction = 65366
Public Const SQLDMOPriv_AllDatabasePrivs = 130944 'Default
    
